(() => {
  const KEY='word-memory-v2', $=id=>document.getElementById(id);
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:[]}catch{return[]}};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let selecting=false,selected=new Set();
  function wrongWords(){const ex=new Set(JSON.parse(localStorage.getItem('word-memory-wrong-excluded')||'[]').map(String));return load().filter(w=>w.word&&w.meaning&&(Number(w.mastery||0)<=2||Number(w.wrongCount||0)>0)&&!ex.has(String(w.id))).sort((a,b)=>(a.mastery||0)-(b.mastery||0)||String(a.word).localeCompare(String(b.word)))}
  function render(){const box=$('wrongList');if(!box)return;const data=wrongWords();if(!data.length){box.innerHTML='<div class="empty"><p>太棒了！目前没有明显薄弱词。</p></div>';update();return}box.innerHTML=`<div class="wrong-toolbar">${selecting?`<label><input id="wrongSelectAll" type="checkbox"> 全选</label><span>已选 ${selected.size} 个</span><button id="wrongCancel" class="secondary" type="button">取消选择</button>`:''}<button id="wrongClearAll" class="danger" type="button">全部删除</button></div>${data.map(w=>`<article class="word-item wrong-item">${selecting?`<label class="wrong-check"><input class="wrong-select" type="checkbox" data-id="${esc(w.id)}" ${selected.has(String(w.id))?'checked':''}></label>`:''}<div class="word-main"><strong>${esc(w.word)}</strong><span>${esc(w.meaning)}${w.unit?' · '+esc(w.unit):''} · 掌握度 ${Number(w.mastery||0)}/6</span></div><div class="word-actions"><button class="secondary wrong-delete" data-id="${esc(w.id)}" type="button">删除</button></div></article>`).join('')}`;box.querySelectorAll('.wrong-select').forEach(c=>c.onchange=()=>{const id=String(c.dataset.id);c.checked?selected.add(id):selected.delete(id);render()});$('wrongSelectAll')?.addEventListener('change',e=>{if(e.target.checked)data.forEach(w=>selected.add(String(w.id)));else selected.clear();render()});$('wrongCancel')?.addEventListener('click',()=>{selecting=false;selected.clear();render();update()});$('wrongClearAll')?.addEventListener('click',()=>{const n=wrongWords().length;if(!confirm(`确定清空错题本中的 ${n} 个单词吗？\n\n只会移除错题本记录，不会删除“我的词库”中的单词。`))return;const ex=new Set(JSON.parse(localStorage.getItem('word-memory-wrong-excluded')||'[]').map(String));data.forEach(w=>ex.add(String(w.id)));localStorage.setItem('word-memory-wrong-excluded',JSON.stringify([...ex]));selected.clear();selecting=false;render();});box.querySelectorAll('.wrong-delete').forEach(b=>b.onclick=()=>removeWrong(String(b.dataset.id)))}
  function removeWrong(id){const w=load().find(x=>String(x.id)===id);if(!w)return;if(!confirm(`确定只从错题本移除“${w.word}”吗？\n\n不会删除我的词库中的这个单词。`))return;const ex=new Set(JSON.parse(localStorage.getItem('word-memory-wrong-excluded')||'[]').map(String));ex.add(id);localStorage.setItem('word-memory-wrong-excluded',JSON.stringify([...ex]));selected.delete(id);render()}
  function update(){const b=$('wrongStudyBtn');if(b)b.textContent=selecting?`开始复习已选（${selected.size}）`:'选择单词开始复习'}
  function begin(){selecting=true;selected.clear();render();update()}
  function bind(){const b=$('wrongStudyBtn');if(b&&!b.dataset.bound){b.dataset.bound='1';b.onclick=()=>selecting?alert(`已选择 ${selected.size} 个单词。`):begin()}}
  bind();if($('wrong')?.classList.contains('active'))render();
})();
