(() => {
  const KEY='word-memory-v2', BACKUP_KEY='word-memory-wrong-study-backup', MODE_KEY='word-memory-wrong-study-selected', EXCLUDE_KEY='word-memory-wrong-excluded';
  const $=id=>document.getElementById(id);
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:[]}catch{return[]}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const excluded=()=>{try{return new Set(JSON.parse(localStorage.getItem(EXCLUDE_KEY)||'[]').map(String))}catch{return new Set()}};
  const setExcluded=s=>localStorage.setItem(EXCLUDE_KEY,JSON.stringify([...s]));
  function wrongWords(){const ex=excluded();return load().filter(w=>w.word&&w.meaning&&(Number(w.mastery||0)<=2||Number(w.wrongCount||0)>0)&&!ex.has(String(w.id))).sort((a,b)=>(a.mastery||0)-(b.mastery||0)||String(a.word).localeCompare(String(b.word)))}
  let selecting=false,selected=new Set();
  function render(){const box=$('wrongList');if(!box)return;const data=wrongWords();if(!data.length){box.innerHTML='<div class="empty"><p>太棒了！目前没有明显薄弱词。</p></div>';updateButton();return}box.innerHTML=`<div class="wrong-toolbar">${selecting?`<label><input id="wrongSelectAll" type="checkbox"> 全选</label><span>已选 ${selected.size} 个</span><button id="wrongCancel" class="secondary" type="button">取消选择</button>`:''}<button id="wrongClearAll" class="danger" type="button">全部删除</button></div>${data.map(w=>`<article class="word-item wrong-item">${selecting?`<label class="wrong-check"><input class="wrong-select" type="checkbox" data-id="${esc(w.id)}" ${selected.has(String(w.id))?'checked':''}></label>`:''}<div class="word-main"><strong>${esc(w.word)}</strong><span>${esc(w.meaning)}${w.unit?' · '+esc(w.unit):''} · 掌握度 ${Number(w.mastery||0)}/6</span></div><div class="word-actions"><button class="secondary wrong-delete" data-id="${esc(w.id)}" type="button">删除</button></div></article>`).join('')}`;box.querySelectorAll('.wrong-select').forEach(c=>c.onchange=()=>{const id=String(c.dataset.id);c.checked?selected.add(id):selected.delete(id);render()});$('wrongSelectAll')?.addEventListener('change',e=>{if(e.target.checked)data.forEach(w=>selected.add(String(w.id)));else selected.clear();render()});$('wrongCancel')?.addEventListener('click',()=>{selecting=false;selected.clear();render();updateButton()});$('wrongClearAll')?.addEventListener('click',()=>{const n=wrongWords().length;if(!n)return;if(!confirm(`确定清空错题本中的 ${n} 个单词吗？\n\n只会从“错题本”移除，不会删除“我的词库”中的单词。`))return;const ex=excluded();data.forEach(w=>ex.add(String(w.id)));setExcluded(ex);selected.clear();selecting=false;render();updateButton()});box.querySelectorAll('.wrong-delete').forEach(b=>b.onclick=()=>removeWrong(String(b.dataset.id)))}
  function removeWrong(id){const w=load().find(x=>String(x.id)===id);if(!w)return;if(!confirm(`确定只从错题本移除“${w.word}”吗？\n\n不会删除我的词库中的这个单词。`))return;const ex=excluded();ex.add(id);setExcluded(ex);selected.delete(id);render()}
  function updateButton(){const b=$('wrongStudyBtn');if(b)b.textContent=selecting?`开始复习已选（${selected.size}）`:'选择单词开始复习'}
  function beginSelection(){selecting=true;selected.clear();render();updateButton()}
  function startSelectedStudy(){const ids=[...selected];if(!ids.length){alert('请先勾选至少 1 个单词。');return}const data=load(),set=new Set(ids),backup=data.map(w=>({id:w.id,nextReview:w.nextReview}));localStorage.setItem(BACKUP_KEY,JSON.stringify(backup));localStorage.setItem(MODE_KEY+'-ids',JSON.stringify(ids));data.forEach(w=>{w.nextReview=set.has(String(w.id))?new Date().toISOString().slice(0,10):'2999-12-31'});save(data);localStorage.setItem(MODE_KEY,'1');location.reload()}
  function finishWrongStudy(){let backup=[],ids=[];try{backup=JSON.parse(localStorage.getItem(BACKUP_KEY)||'[]')}catch{}try{ids=JSON.parse(localStorage.getItem(MODE_KEY+'-ids')||'[]').map(String)}catch{}if(!backup.length){localStorage.removeItem(MODE_KEY);localStorage.removeItem(MODE_KEY+'-ids');return}const set=new Set(ids),data=load();backup.forEach(b=>{if(set.has(String(b.id)))return;const w=data.find(x=>String(x.id)===String(b.id));if(w)w.nextReview=b.nextReview});save(data);localStorage.removeItem(BACKUP_KEY);localStorage.removeItem(MODE_KEY);localStorage.removeItem(MODE_KEY+'-ids');location.reload()}
  function bind(){const b=$('wrongStudyBtn');if(b&&!b.dataset.wrongFixBound){b.dataset.wrongFixBound='1';b.addEventListener('click',()=>selecting?startSelectedStudy():beginSelection())}document.querySelector('.tab[data-tab="wrong"]')?.addEventListener('click',()=>setTimeout(()=>{selecting=false;selected.clear();render();updateButton()},80))}
  function sessionButton(){if(localStorage.getItem(MODE_KEY)!=='1')return;const top=$('study')?.querySelector('.card-top');if(!top||$('wrongStudyExitBtn'))return;const b=document.createElement('button');b.id='wrongStudyExitBtn';b.className='secondary';b.type='button';b.textContent='结束错词复习';b.onclick=finishWrongStudy;top.appendChild(b)}
  bind();sessionButton();if($('wrong')?.classList.contains('active'))render();
})();
